### ISSUE TITLE
Detection of -ne and -que enclitics is too greedy 

### ISSUE THREAD

**Issue by pjheslin** [chartes/deucalion-model-lasla#10]
I've just started playing with Deucalion.  It's very nice!  Congratulations!

One issue with the tagging is that it is too eager to detach -ne:

solitudi	solitudus	NOMcom	Case=Dat|Numb=Sing	solitudi
-ne	ne2	CONcoo	MORPH=empty	-ne
habitudi	habitudi	VER	Case=Nom|Numb=Sing	habitudi
-ne	ne2	CONcoo	MORPH=empty	-ne

Likewise for -que:

co	co	NOMcom	Case=Abl|Numb=Sing	co
-que	que	CONcoo	MORPH=empty	-que

The obvious words (quoque, neque, denique, etc.) are OK: they are presumably protected from this behaviour because they are lemmata rather than inflected forms.

Is this the sort of thing that can easily be tweaked to fix, or is it intrinsic to the model?

**Comment by PonteIneptique** [comment]
Hi! Thanks :)
Before I answer, can I ask how proficient in python are you? Just to know
how much details I can go into

Le jeu. 5 mars 2020 à 11:15 AM, pjheslin <notifications@github.com> a
écrit :

**Comment by pjheslin** [comment]
I have a reasonable knowledge of Python, but I'm more familiar with keras/tensorflow than pytorch.

**Comment by PonteIneptique** [comment]
I am giving a lecture all day, I'll get back to you soon. But you should
have a look at github.com/hipster-philology/nlp-pie-taggers which handles
that better.

**Comment by pjheslin** [comment]
I've installed nlp-pie-taggers and I think I have installed all of the prerequisites correctly, including cltk and its Latin data.

When I run: 
`pie-extended tag lasla test.txt`
I get:
`test.txt could not be lemmatized`

When I run the API example code from the Readme, I get:
`TypeError: tokenize() got an unexpected keyword argument 'replacements'`

Here is the full backtrace:

$ python3 test-pie.py
fatal: not a git repository (or any of the parent directories): .git
2020-03-05 16:21:40,031 : Model /usr/local/lib/python3.7/site-packages/pie_extended/downloads/lasla/model.tar was serialized with a previous version of `pie`. This might result in issues. Model commit is aa1c347, whereas current `pie` commit is 050815e.
Traceback (most recent call last):
  File "test-pie.py", line 19, in <module>
    print(tagger.tag_str(sentence_group, iterator=iterator, processor=processor) )
  File "/usr/local/lib/python3.7/site-packages/pie_extended/tagger.py", line 37, in tag_str
    return list(self.iter_tag_token(data, iterator, processor=processor))
  File "/usr/local/lib/python3.7/site-packages/pie_extended/tagger.py", line 47, in iter_tag_token
    size=self.batch_size):
  File "/usr/local/lib/python3.7/site-packages/pie/utils.py", line 36, in chunks
    for s in it:
  File "/usr/local/lib/python3.7/site-packages/pie_extended/pipeline/iterators/proto.py", line 104, in __call__
    for sentence in self.tokenizer.sentence_tokenizer(data, lower=lower):
  File "/usr/local/lib/python3.7/site-packages/pie_extended/models/lasla/tokenizer.py", line 88, in sentence_tokenizer
    sentences.append(self.word_tokenizer(sent))
  File "/usr/local/lib/python3.7/site-packages/pie_extended/pipeline/tokenizers/memorizing.py", line 24, in word_tokenizer
    for token in self._real_word_tokenizer(text, lower):
  File "/usr/local/lib/python3.7/site-packages/pie_extended/models/lasla/tokenizer.py", line 69, in _real_word_tokenizer
    enclitics_exceptions=ENCLITIC_EXCEPTIONS
TypeError: tokenize() got an unexpected keyword argument 'replacements'

**Comment by PonteIneptique** [comment]
It looks like you installed the default CLTK instead of the branch version. Please try to do 
```shell
pip install --upgrade https://github.com/PonteIneptique/cltk/archive/latin_clitics_exceptions.zip
```

**Comment by PonteIneptique** [comment]
Note that when you have an error like the first one, you can run it again with --debug which will raise and show the stack trace

**Comment by pjheslin** [comment]
Thanks.  It works now.  Results are somewhat better in these cases, but not perfect:

solitudine      solitudo        NOMcom  Case=Abl|Numb=Sing      solitudine
habitudi        habitudi        VER     Case=Gen|Numb=Sing|Voice=Act    habitudi
-ne     ne2     ADVint  MORPH=empty     -ne
coque   coque   ADV     MORPH=empty     coque

**Comment by PonteIneptique** [comment]
I would propose we move the discussion to the repository of nlp-pie-taggers ?

**Comment by pjheslin** [comment]
OK
