### ISSUE TITLE
Treatment of punctuation and abbreviations

### ISSUE THREAD

**Issue by Stormur** [chartes/deucalion-model-lasla#4]
It seems that the POS-tagger applies some heuristics to split sentences. These, however, are not able to cope with abbreviations written as _Ti._ (_Tiberius_) or _Cn._ (_Cneus_), which are treated like _Ti + ._ . This also conflicts with input already split in sentences (with e.g. space-separated words) or with a one-token-per-line format, where one would want each token analysed as it is. 

Do you think it is possible to implement such behaviours, or at least to document how the automatic splitting works?

Thank you!

**Comment by PonteIneptique** [comment]
Honnestly, that is one point I have yet to enhance. The tokenizer is defined here https://github.com/chartes/deucalion-model-lasla/blob/master/flaskapp.py#L61-L85 and reuse https://github.com/emanjavacas/pie/blob/master/pie/tagger.py#L27-L35

**Comment by PonteIneptique** [comment]
Note that a fix is coming for this.

**Comment by PonteIneptique** [comment]
A fix has been incorporated ;)
